Module: Tms
Author: jian玄冰
DataSource:
  Name: DbTableSchema
  Parameters:
    DbName: Tms
    DbProvider: SqlServer
    ConnectionString: Data Source=DESKTOP-I6SANBT\JIAN;Initial Catalog=Tms;User Id=sa;Password=jian123456;Integrated Security=True
Language: CSharp
TemplateEngine:
  Name: Razor
  Root: Bing
  Path: G:\Git\SmartCode\Bing.GenerateDemo\bin\Debug\netcoreapp2.2\RazorTemplates
Output:
  Type: File
  Path: 'D:\demo\generate'

NamingConverter:
  Table:
    Tokenizer:
      Type: Default
    Converter:
      Type: Default
  View:
    Tokenizer:
      Type: Default
    Converter:
      Type: Default
  Column:
    Tokenizer:
      Type: Default
    Converter:
      Type: Default

Build:
  ClearDir:
    Type: Clear
    Parameters:
      Dirs: '.'
  Scaffolding:
    Type: MultiTemplate
    Output:
      Path: '.'
    Parameters:
      Templates: [{Key: 'Sln.cshtml', Output: { Name: '{{Project.Module}}', Extension: '.sln'}}, 
      {Key: 'Sln-Directory.Build.cshtml', Output: { Name: 'Directory.Build', Extension: '.props'}}, 
      {Key: 'Sln-Version.cshtml', Output: { Path: 'build', Name: 'version', Extension: '.props'}},
      {Key: 'Sln-Dockerfile.cshtml', Output: { Name: 'Dockerfile', Extension: ''}}, 
      {Key: 'Sln-DockerIgnore.cshtml', Output: { Name: '.dockerignore', Extension: ''}}, 
      {Key: 'Sln-GitIgnore.cshtml', Output: { Name: '.gitignore', Extension: ''}}, 
      {Key: 'Proj-Infrastructure.cshtml', Output: { Path: 'src/{{Project.Module}}.Infrastructure', Name: '{{Project.Module}}.Infrastructure', Extension: '.csproj'}}, 
      {Key: 'Proj-Data.cshtml', Output: { Path: 'src/{{Project.Module}}.Data', Name: '{{Project.Module}}.Data', Extension: '.csproj'}}, 
      {Key: 'Proj-Service.cshtml', Output: { Path: 'src/{{Project.Module}}.Service', Name: '{{Project.Module}}.Service', Extension: '.csproj'}}, ]